# Generated by `mise run brew:generate`. Do not edit.
# Source: union of tasks/*/Brewfile.

brew "cloudflared"
brew "direnv"
brew "the_silver_searcher"
cask "1password"
cask "1password-cli"
cask "claude"
cask "claude-code"
cask "docker-desktop"
cask "iterm2"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Spark Desktop", id: 6445813049
vscode "anthropic.claude-code"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "ms-azuretools.vscode-containers"
