#!/usr/bin/env bash
#MISE description="Install Oh My Zsh, Powerlevel10k, Powerline fonts, zsh Brewfile, and symlink configs"
#MISE depends=["brew:apply"]
#MISE sources=["tasks/zsh/Brewfile"]
set -euo pipefail

TASK_DIR="$MISE_PROJECT_ROOT/tasks/zsh"

source "$MISE_PROJECT_ROOT/lib/brew.sh"
source "$MISE_PROJECT_ROOT/lib/symlink.sh"
ensure_brew "$TASK_DIR/Brewfile"

if [[ -d "$HOME/.oh-my-zsh/.git" ]]; then
  echo "OhMyZSH already installed, checking for deltas"
  git -C "$HOME/.oh-my-zsh" fetch --quiet origin master
  behind=$(git -C "$HOME/.oh-my-zsh" rev-list --count HEAD..origin/master)
  ahead=$(git -C "$HOME/.oh-my-zsh" rev-list --count origin/master..HEAD)
  local_changes=$(git -C "$HOME/.oh-my-zsh" status --short)

  if [[ -n "$local_changes" ]]; then
    echo
    echo "Local modifications:"
    echo "$local_changes"
  fi
  if (( behind > 0 )); then
    echo
    echo "$behind commit(s) behind upstream:"
    git -C "$HOME/.oh-my-zsh" log --oneline HEAD..origin/master | head -20
  fi
  if (( ahead > 0 )); then
    echo
    echo "$ahead local commit(s) ahead of upstream"
  fi
  if [[ -z "$local_changes" ]] && (( behind == 0 && ahead == 0 )); then
    echo "Up to date with upstream"
  fi
else
  sh -c "export RUNZSH=no && $(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  # Move OMZ's generated .zshrc aside so link_dotfile below can take over.
  [[ -f "$HOME/.zshrc" && ! -L "$HOME/.zshrc" ]] && mv "$HOME/.zshrc" "$HOME/.zshrc.omz-default"
fi

P10K_DIR="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
if [[ -d "$P10K_DIR/.git" ]]; then
  echo "Updating powerlevel10k"
  git -C "$P10K_DIR" pull --quiet
else
  echo "Installing powerlevel10k"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$P10K_DIR"
fi

AUTOSUGGESTIONS_DIR="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
if [[ -d "$AUTOSUGGESTIONS_DIR/.git" ]]; then
  echo "Updating zsh-autosuggestions"
  git -C "$AUTOSUGGESTIONS_DIR" pull --quiet
else
  echo "Installing zsh-autosuggestions"
  git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions "$AUTOSUGGESTIONS_DIR"
fi

SYNTAXHIGHLIGHTING_DIR="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"
if [[ -d "$SYNTAXHIGHLIGHTING_DIR/.git" ]]; then
  echo "Updating zsh-syntax-highlighting"
  git -C "$SYNTAXHIGHLIGHTING_DIR" pull --quiet
else
  echo "Installing zsh-syntax-highlighting"
  git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting "$SYNTAXHIGHLIGHTING_DIR"
fi


# Symlink configs unconditionally (fixes the case where OMZ was already
# installed but ~/.zshrc was never linked).
link_dotfile "$TASK_DIR/zshrc" "$HOME/.zshrc"
link_dotfile "$TASK_DIR/p10k.zsh" "$HOME/.p10k.zsh"

FONTS_DIR="$HOME/.powerline-fonts"
if [[ -d "$FONTS_DIR/.git" ]]; then
  echo "Updating powerline fonts"
  git -C "$FONTS_DIR" pull --quiet
else
  echo "Installing powerline fonts"
  git clone --depth=1 https://github.com/powerline/fonts.git "$FONTS_DIR"
fi
"$FONTS_DIR/install.sh"
